# Generated by Django 3.1.7 on 2021-03-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='激活状态'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='用户邮箱'),
        ),
    ]
